// Generated by tools/subset-icons.py from Fluent System Icons 1.1.341 (Regular, MIT). Don't edit.

namespace WafeControl.Mobile.Helpers;

/// <summary>
/// Glyphs of the FluentIcons font; see DESIGN.md, section 6.
/// </summary>
public static class FluentIcons
{
    public const string FontFamily = "FluentIcons";

    public const string Add = "\uF10A";
    public const string Airplane = "\uF110";
    public const string ArrowClockwise = "\uF13E";
    public const string ArrowExportLtr = "\uE0C8";
    public const string ArrowImport = "\uF15A";
    public const string CalendarLtr = "\uE24F";
    public const string Checkmark = "\uF295";
    public const string CheckmarkCircle = "\uF298";
    public const string ChevronRight = "\uF2B1";
    public const string Clock = "\uF2DE";
    public const string CloudOff = "\uF2EA";
    public const string Cube = "\uF336";
    public const string DarkTheme = "\uF33C";
    public const string Delete = "\uF34D";
    public const string Dismiss = "\uF36A";
    public const string Drop = "\uE591";
    public const string ErrorCircle = "\uF3F2";
    public const string Filter = "\uF407";
    public const string Flash = "\uE619";
    public const string Globe = "\uF45B";
    public const string Home = "\uF481";
    public const string Info = "\uF4A4";
    public const string LocalLanguage = "\uF4F4";
    public const string LockClosed = "\uE790";
    public const string Mail = "\uF507";
    public const string Molecule = "\uF65A";
    public const string Person = "\uF5BE";
    public const string PersonSupport = "\uF5DA";
    public const string Power = "\uF60F";
    public const string Rename = "\uF66A";
    public const string Settings = "\uF6AA";
    public const string SignOut = "\uF6DA";
    public const string Timer = "\uF827";
    public const string TopSpeed = "\uF831";
    public const string Warning = "\uF86A";
    public const string WeatherMoon = "\uF87E";
    public const string WeatherSunny = "\uF8A2";
    public const string WifiOff = "\uEE5A";
}
