"""Builds the mobile app's icon font: a subset of Fluent System Icons (Regular, MIT license).

Writes src/WafeControl.Mobile/Resources/Fonts/FluentIcons.ttf and src/WafeControl.Mobile/Helpers/FluentIcons.cs.
To add an icon, add its name (without the ic_fluent_ prefix and size suffix) to ICONS and run the script.
"name@20" takes another size's glyph, for icons whose 24 px glyph is broken in the font.

    pip install fonttools
    python tools/subset-icons.py

See DESIGN.md, section 6.
"""

import io
import json
import pathlib
import urllib.request

from fontTools import subset

VERSION = "1.1.341"
SOURCE = f"https://cdn.jsdelivr.net/gh/microsoft/fluentui-system-icons@{VERSION}/fonts/FluentSystemIcons-Regular"
SIZE = 24

ICONS = [
    "add",
    "airplane",
    "arrow_clockwise",
    "arrow_export_ltr",
    "arrow_import",
    "calendar_ltr",
    "checkmark",
    # The 24 px glyph is a compass in 1.1.341.
    "checkmark_circle@20",
    "chevron_right",
    "clock",
    "cloud_off",
    "cube",
    "dark_theme",
    "delete",
    "dismiss",
    "drop",
    "error_circle",
    "filter",
    "flash",
    "globe",
    "home",
    "info",
    "local_language",
    "lock_closed",
    "mail",
    "molecule",
    "person",
    "person_support",
    "power",
    "rename",
    "settings",
    "sign_out",
    "timer",
    "top_speed",
    "warning",
    "weather_moon",
    "weather_sunny",
    "wifi_off",
]

ROOT = pathlib.Path(__file__).resolve().parent.parent
MOBILE = ROOT / "src" / "WafeControl.Mobile"


def download(url: str) -> bytes:
    with urllib.request.urlopen(url) as response:
        return response.read()


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def main() -> None:
    codepoints = json.loads(download(SOURCE + ".json"))
    glyphs = {}
    for icon in ICONS:
        name, _, size = icon.partition("@")
        glyphs[name] = codepoints[f"ic_fluent_{name}_{size or SIZE}_regular"]

    options = subset.Options()
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    font = subset.load_font(io.BytesIO(download(SOURCE + ".ttf")), options)
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=glyphs.values())
    subsetter.subset(font)
    subset.save_font(font, str(MOBILE / "Resources" / "Fonts" / "FluentIcons.ttf"), options)

    lines = [
        "// Generated by tools/subset-icons.py from Fluent System Icons " + VERSION + " (Regular, MIT). Don't edit.",
        "",
        "namespace WafeControl.Mobile.Helpers;",
        "",
        "/// <summary>",
        "/// Glyphs of the FluentIcons font; see DESIGN.md, section 6.",
        "/// </summary>",
        "public static class FluentIcons",
        "{",
        '    public const string FontFamily = "FluentIcons";',
        "",
    ]
    lines += [f'    public const string {pascal(name)} = "\\u{code:04X}";' for name, code in sorted(glyphs.items())]
    lines += ["}", ""]
    (MOBILE / "Helpers" / "FluentIcons.cs").write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(glyphs)} icons")


if __name__ == "__main__":
    main()
